<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros [
  <!ELEMENT libros (libro+)>
  <!ELEMENT libro (titulo, autor, descripcion)>
  <!ATTLIST libro id CDATA #REQUIRED>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT autor EMPTY>
  <!ATTLIST autor nombre CDATA #REQUIRED>
  <!ELEMENT descripcion (#PCDATA)>
]>
<libros>
  <libro id="quijote">
    <titulo>El Quijote</titulo>
    <autor nombre="cervantes"></autor>
    <descripcion>Es el mejor libro de Cervantes.</descripcion>
  </libro>
</libros>
